Error state - causes the below
$ npm run dev

> ~TODO~@0.0.1 dev
> svelte-kit dev

 > html:/home/domweldon/somewhere/on/my/filesystem/my-app/src/routes/index.svelte:2:12: error: Expected ";" but found ":"
    2 │     let name: string = "world"
      ╵             ^

> Build failed with 1 error:
html:/home/domweldon/somewhere/on/my/filesystem/my-app/src/routes/index.svelte:2:12: error: Expected ";" but found ":"
Error: Build failed with 1 error:
html:/home/domweldon/somewhere/on/my/filesystem/my-app/src/routes/index.svelte:2:12: error: Expected ";" but found ":"
    at failureErrorWithLog (/home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:1451:15)
    at /home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:1129:7)
    at /home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:1238:14
    at /home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/domweldon/somewhere/on/my/filesystem/my-app/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)